version: "3.8"

services:
  dropbox-bot:
    build: .
    image: dropbox-bot-cli
    container_name: dropbox-bot-cli
    volumes:
      - ./data:/app/data
    restart: "no"
    # Contoh argumen CLI saat container dijalankan:
    command: >
      --alias "CLI-Worker" 
      --url "https://www.dropbox.com/register" 
      --source "auto" 
      --domain "kywa.uk" 
      --count 10 
      --password-mode "random" 
      --timeout 120 
      --retry 3 
      --devices "desktop,mobile"
